### ISSUE TITLE
panic: not suppose to be called

### ISSUE THREAD

**Issue by jkassis** [lni/dragonboat#151]
Trying to track this down, but posting in case this is something on the dragonboat side. This comes up when starting my cluster and switching from pebbledb to rocksdb. Cluster comes up find with pebbledb, but I get this with the default LogDBFactory.

> Note: for reported bugs, please fill in the following details. bug reports without detailed steps on how to reproduce will be automatically closed. 

### Dragonboat version
v3.2.9

### Actual behavior
panic: not suppose to be called

goroutine 16 [running]:
github.com/lni/dragonboat/v3/internal/logdb.newDefaultKVStore(0xc00011e000, 0x91, 0xc00011e0a0, 0x91, 0x4f51480, 0x5714480, 0x91, 0xc0005a10b8, 0x48ebe71, 0xc0001fbce0)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/kv_custom.go:33 +0xd7
github.com/lni/dragonboat/v3/internal/logdb.hasBatchedRecord(0xc00011e000, 0x91, 0xc00011e0a0, 0x91, 0x4f51480, 0x5714480, 0x4db7ac8, 0x0, 0x0, 0x0)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/rdb.go:79 +0xa0
github.com/lni/dragonboat/v3/internal/logdb.checkAllShards(0xc0001a0700, 0x10, 0x10, 0xc0001a0800, 0x10, 0x10, 0x4f51480, 0x5714480, 0x4db7ac8, 0x4b807c0, ...)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/sharded_rdb.go:58 +0x1d4
github.com/lni/dragonboat/v3/internal/logdb.OpenShardedRDB(0xc0001a0700, 0x10, 0x10, 0xc0001a0800, 0x10, 0x10, 0x100, 0x4f51480, 0x5714480, 0x4db7ac8, ...)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/sharded_rdb.go:84 +0x993
github.com/lni/dragonboat/v3/internal/logdb.NewLogDB(0xc000115c00, 0x1, 0x1, 0xc000115c00, 0x1, 0x1, 0xc000110100, 0x4f51480, 0x5714480, 0x4db7ac8, ...)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/logdb.go:72 +0x338
github.com/lni/dragonboat/v3/internal/logdb.NewDefaultLogDB(...)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/logdb.go:47
github.com/lni/dragonboat/v3.(*NodeHost).createLogDB.func1(0xc000115c00, 0x1, 0x1, 0xc000115c00, 0x1, 0x1, 0x0, 0x1, 0xc0003577a0, 0xc0007a2b40)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/nodehost.go:1639 +0xa2
github.com/lni/dragonboat/v3/internal/logdb.GetLogDBInfo(0xc0005a15c8, 0xc000115bd0, 0x1, 0x1, 0x4f51480, 0x5714480, 0x0, 0x0, 0x0, 0x0)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/internal/logdb/logdb.go:107 +0x309
github.com/lni/dragonboat/v3.(*NodeHost).createLogDB(0xc0000f8240, 0xa, 0xc0007a2340, 0x36, 0xc0007a22c0, 0x3b, 0x1, 0xc000794610, 0xe, 0xc000216240, ...)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/nodehost.go:1647 +0x153
github.com/lni/dragonboat/v3.NewNodeHost(0xa, 0xc0007a2340, 0x36, 0xc0007a22c0, 0x3b, 0x1, 0xc000794610, 0xe, 0xc000216240, 0xe, ...)
	/Users/jkassis/go/pkg/mod/github.com/lni/dragonboat/v3@v3.2.8/nodehost.go:326 +0x820
github.com/jkassis/shinetribe.net/core/kittie.(*ServiceRaftDBDisk).Play(0xc0001a0300, 0x0, 0x0)
	/Users/jkassis/code/jerrie/core/kittie/serviceRaftDBDisk.go:124 +0x57a
github.com/jkassis/shinetribe.net/core/kittie.(*ServiceRaftNode).Play(0xc0007da360, 0x0, 0x0)
	/Users/jkassis/code/jerrie/core/kittie/serviceRaftNode.go:279 +0xa5
github.com/jkassis/shinetribe.net/core/kittie.(*ServiceRaftCluster).PlayOne(0xc0007da240, 0x0, 0xc000114030, 0x2, 0x2, 0x0)
	/Users/jkassis/code/jerrie/core/kittie/serviceRaftCluster.go:343 +0x690
github.com/jkassis/shinetribe.net/core/kittie.(*ServiceRaftCluster).Play.func1(0xc0007945a8, 0xc0007da240, 0xc0000920c0)
	/Users/jkassis/code/jerrie/core/kittie/serviceRaftCluster.go:258 +0xda
created by github.com/jkassis/shinetribe.net/core/kittie.(*ServiceRaftCluster).Play
	/Users/jkassis/code/jerrie/core/kittie/serviceRaftCluster.go:255 +0x2eb
exit status 2

**Comment by jkassis** [comment]
ahh... this happens when using rocks in code, but running process with `dragonboat_no_rocksdb` go build flag. Just a little gotcha when switching back and forth between pebble and rocks.
