### ISSUE TITLE
Nodes can be loaded from two incarnations

### ISSUE THREAD

**Issue by lni** [lni/dragonboat#194]
Saw this in TestJoinedClusterCanBeRestartedOrJoinedAgain. 

The underlying issue here is that nh.stopNode() doesn't wait until the node is actually offloaded from the engine. 

This bug is expected to have minimum impact on users as applications are not expected to stop a node and then immediately restart it. 

```
2021-07-24T13:12:21.4727461Z === RUN   TestJoinedClusterCanBeRestartedOrJoinedAgain
2021-07-24T13:12:21.4762446Z 2021-07-24 13:12:21.475959 I | dragonboat: go version: go1.15.14, linux/amd64
2021-07-24T13:12:21.4764029Z 2021-07-24 13:12:21.476156 I | dragonboat: dragonboat version: 3.4.0 (Dev)
2021-07-24T13:12:21.4765403Z 2021-07-24 13:12:21.476218 W | config: mutual TLS disabled, communication is insecure
2021-07-24T13:12:21.4766935Z 2021-07-24 13:12:21.476548 I | dragonboat: DeploymentID set to 1
2021-07-24T13:12:21.4902741Z 2021-07-24 13:12:21.489883 I | dragonboat: LogDB info received, shard 0, busy false
2021-07-24T13:12:21.4989446Z 2021-07-24 13:12:21.498611 I | dragonboat: LogDB info received, shard 1, busy false
2021-07-24T13:12:21.5095677Z 2021-07-24 13:12:21.509186 I | dragonboat: LogDB info received, shard 2, busy false
2021-07-24T13:12:21.5159969Z 2021-07-24 13:12:21.515729 I | logdb: using plain logdb
2021-07-24T13:12:21.5164227Z 2021-07-24 13:12:21.516235 I | dragonboat: LogDB info received, shard 3, busy false
2021-07-24T13:12:21.5178624Z 2021-07-24 13:12:21.517655 I | dragonboat: logdb memory limit: 2048 MBytes
2021-07-24T13:12:21.5188584Z 2021-07-24 13:12:21.518657 I | dragonboat: NodeHost ID: nhid-12226359585691675605
2021-07-24T13:12:21.5190402Z 2021-07-24 13:12:21.518703 I | dragonboat: using regular node registry
2021-07-24T13:12:21.5191806Z 2021-07-24 13:12:21.518760 I | dragonboat: filesystem error injection mode enabled: false
2021-07-24T13:12:21.5279878Z 2021-07-24 13:12:21.527739 I | transport: transport type: go-tcp-transport
2021-07-24T13:12:21.5327787Z 2021-07-24 13:12:21.531604 I | dragonboat: transport type: go-tcp-transport
2021-07-24T13:12:21.5382632Z 2021-07-24 13:12:21.531663 I | dragonboat: logdb type: sharded-pebble
2021-07-24T13:12:21.5383706Z 2021-07-24 13:12:21.531693 I | dragonboat: nodehost address: localhost:26001
2021-07-24T13:12:21.5384791Z 2021-07-24 13:12:21.535548 I | dragonboat: [00001:00001] replaying raft logs
2021-07-24T13:12:21.5385738Z 2021-07-24 13:12:21.535702 I | raft: [00001:00001] created, initial: false, new: true
2021-07-24T13:12:21.5386815Z 2021-07-24 13:12:21.535736 W | config: ElectionRTT is not a magnitude larger than HeartbeatRTT
2021-07-24T13:12:21.5387868Z 2021-07-24 13:12:21.535787 I | raft: [00001:00001] raft log rate limit enabled: false, 0
2021-07-24T13:12:21.5388800Z 2021-07-24 13:12:21.535851 I | raft: [f:1,l:0,t:0,c:0,a:0] [00001:00001] t0 became follower
2021-07-24T13:12:21.5412883Z 2021-07-24 13:12:21.541037 I | dragonboat: [00001:00001] replaying raft logs
2021-07-24T13:12:21.5431845Z 2021-07-24 13:12:21.542937 I | raft: [00001:00001] created, initial: false, new: true
2021-07-24T13:12:21.5434299Z 2021-07-24 13:12:21.542989 W | config: ElectionRTT is not a magnitude larger than HeartbeatRTT
2021-07-24T13:12:21.5451490Z 2021-07-24 13:12:21.543053 I | raft: [00001:00001] raft log rate limit enabled: false, 0
2021-07-24T13:12:21.5452528Z 2021-07-24 13:12:21.543114 I | raft: [f:1,l:0,t:0,c:0,a:0] [00001:00001] t0 became follower
2021-07-24T13:12:21.5453457Z 2021-07-24 13:12:21.543364 C | dragonboat: [00001:00001] from two incarnations found
2021-07-24T13:12:21.5482298Z panic: [00001:00001] from two incarnations found
2021-07-24T13:12:21.5482727Z 
2021-07-24T13:12:21.5483145Z goroutine 5088 [running]:
2021-07-24T13:12:21.5484057Z github.com/lni/goutils/logutil/capnslog.(*PackageLogger).Panicf(0xc0001cc3e0, 0x13a8c1e, 0x1e, 0xc0001b5e40, 0x1, 0x1)
2021-07-24T13:12:21.5485829Z 	/home/runner/go/pkg/mod/github.com/lni/goutils@v1.3.1-0.20210517080819-7f56813dc438/logutil/capnslog/pkg_logger.go:88 +0x165
2021-07-24T13:12:21.5486930Z github.com/lni/dragonboat/v3/logger.(*capnsLog).Panicf(0xc000010030, 0x13a8c1e, 0x1e, 0xc0001b5e40, 0x1, 0x1)
2021-07-24T13:12:21.5488026Z 	/home/runner/work/dragonboat/dragonboat/logger/capnslogger.go:74 +0x85
2021-07-24T13:12:21.5489108Z github.com/lni/dragonboat/v3/logger.(*dragonboatLogger).Panicf(0xc0000909f0, 0x13a8c1e, 0x1e, 0xc0001b5e40, 0x1, 0x1)
2021-07-24T13:12:21.5490512Z 	/home/runner/work/dragonboat/dragonboat/logger/logger.go:132 +0x83
2021-07-24T13:12:21.5491671Z github.com/lni/dragonboat/v3.(*engine).loadBucketNodes.func1(0x1, 0xc0001c4300, 0x1)
2021-07-24T13:12:21.5492676Z 	/home/runner/work/dragonboat/dragonboat/engine.go:1251 +0x38b
2021-07-24T13:12:21.5493713Z github.com/lni/dragonboat/v3.(*NodeHost).forEachCluster.func1(0x125e520, 0x1c28ca8, 0x138d880, 0xc0001c4300, 0x203000)
2021-07-24T13:12:21.5494786Z 	/home/runner/work/dragonboat/dragonboat/nodehost.go:1451 +0x96
2021-07-24T13:12:21.5495517Z sync.(*Map).Range(0xc0000b0aa8, 0xc000bd3a28)
2021-07-24T13:12:21.5496264Z 	/opt/hostedtoolcache/go/1.15.14/x64/src/sync/map.go:345 +0x16c
2021-07-24T13:12:21.5497151Z github.com/lni/dragonboat/v3.(*NodeHost).forEachCluster(0xc0000b0a80, 0xc0010fc200, 0x0)
2021-07-24T13:12:21.5498699Z 	/home/runner/work/dragonboat/dragonboat/nodehost.go:1450 +0xc5
2021-07-24T13:12:21.5499811Z github.com/lni/dragonboat/v3.(*engine).loadBucketNodes(0xc0002d0140, 0x2, 0x1, 0xc0008fbf20, 0x14f1620, 0xc0005e69d0, 0x2, 0xc0008fbf20, 0xc0003bcec8, 0x0, ...)
2021-07-24T13:12:21.5501013Z 	/home/runner/work/dragonboat/dragonboat/engine.go:1248 +0x294
2021-07-24T13:12:21.5501966Z github.com/lni/dragonboat/v3.(*engine).load(0xc0002d0140, 0x2, 0x1, 0xc0008fbf20, 0x2, 0xc0000a4b40, 0xc0008fbf20, 0x1)
2021-07-24T13:12:21.5503114Z 	/home/runner/work/dragonboat/dragonboat/engine.go:1074 +0xb7
2021-07-24T13:12:21.5503954Z github.com/lni/dragonboat/v3.(*engine).loadApplyNodes(...)
2021-07-24T13:12:21.5504820Z 	/home/runner/work/dragonboat/dragonboat/engine.go:1165
2021-07-24T13:12:21.5505678Z github.com/lni/dragonboat/v3.(*engine).applyWorkerMain(0xc0002d0140, 0x2)
2021-07-24T13:12:21.5506602Z 	/home/runner/work/dragonboat/dragonboat/engine.go:1150 +0x510
2021-07-24T13:12:21.5507459Z github.com/lni/dragonboat/v3.newExecEngine.func3()
2021-07-24T13:12:21.5508351Z 	/home/runner/work/dragonboat/dragonboat/engine.go:1038 +0x4b
2021-07-24T13:12:21.5509340Z github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1(0xc000a0f040, 0xc00003d6e0, 0x0, 0x0, 0xc00085d240)
2021-07-24T13:12:21.5510883Z 	/home/runner/go/pkg/mod/github.com/lni/goutils@v1.3.1-0.20210517080819-7f56813dc438/syncutil/stopper.go:79 +0x64
2021-07-24T13:12:21.5511869Z created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
2021-07-24T13:12:21.5513149Z 	/home/runner/go/pkg/mod/github.com/lni/goutils@v1.3.1-0.20210517080819-7f56813dc438/syncutil/stopper.go:74 +0xc5
2021-07-24T13:12:21.5651812Z FAIL	github.com/lni/dragonboat/v3	9.564s
2021-07-24T13:12:21.5655619Z FAIL
```

**Comment by lni** [comment]
This is actually a feature not a bug. 

The idea is once a node is removed from the NodeHost, it is not suppose to be restarted using the current API. There are code to detect such restarted node and panic. 

There might be use cases which do require nodes to be restarted, e.g. taken offline for maintenance and then restart later. To simply the APIs, might just wait for the node to be fully unloaded before the return of StopCluster.

**Comment by lni** [comment]
will be tracked as a new feature in #210
