### ISSUE TITLE
panic when save snapshot

### ISSUE THREAD

**Issue by gensmusic** [lni/dragonboat#36]
```
2019-03-20 14:19:45.212475 I | dragonboat: [00017:00003] snapshotted, index 101, term 2, file count 2
2019-03-20 14:19:45.236230 C | raftpb: file tmp/node/127-0-0-1-2224/boy-OptiPlex-3050/00000000000000000001/snapshot-part-17/snapshot-17-3/snapshot-0000000000000065/snapshot-0000000000000065.gbsnap size 1204, expect 1040
2019-03-20 14:19:45.236273 E | utils: worker is panicing, file tmp/node/127-0-0-1-2224/boy-OptiPlex-3050/00000000000000000001/snapshot-part-17/snapshot-17-3/snapshot-0000000000000065/snapshot-0000000000000065.gbsnap size 1204, expect 1040
panic: file tmp/node/127-0-0-1-2224/boy-OptiPlex-3050/00000000000000000001/snapshot-part-17/snapshot-17-3/snapshot-0000000000000065/snapshot-0000000000000065.gbsnap size 1204, expect 1040 [recovered]
	panic: file tmp/node/127-0-0-1-2224/boy-OptiPlex-3050/00000000000000000001/snapshot-part-17/snapshot-17-3/snapshot-0000000000000065/snapshot-0000000000000065.gbsnap size 1204, expect 1040

goroutine 109 [running]:
github.com/lni/dragonboat/internal/utils/syncutil.(*Stopper).runWorker.func1.1()
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/internal/utils/syncutil/stopper.go:84 +0xeb
panic(0xb183c0, 0xc04ed445a0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/lni/dragonboat/internal/utils/logutil/capnslog.(*PackageLogger).Panicf(0xc04edef0a0, 0xc4ad79, 0x1a, 0xc002d8ff20, 0x3, 0x3)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/internal/utils/logutil/capnslog/pkg_logger.go:83 +0x135
github.com/lni/dragonboat/logger.(*capnsLog).Panicf(0xc0000be668, 0xc4ad79, 0x1a, 0xc002d8ff20, 0x3, 0x3)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/logger/capnslogger.go:73 +0x60
github.com/lni/dragonboat/logger.(*dragonboatLogger).Panicf(0xc00017b890, 0xc4ad79, 0x1a, 0xc002d8ff20, 0x3, 0x3)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/logger/logger.go:120 +0x74
github.com/lni/dragonboat/raftpb.checkFileSize(0xc04f1f0460, 0x99, 0x410)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/raftpb/raft.go:242 +0x1f5
github.com/lni/dragonboat/raftpb.(*Snapshot).Validate(0xc04cb48b40, 0xc04f1f0460)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/raftpb/raft.go:253 +0x56
github.com/lni/dragonboat.(*node).saveSnapshot(0xc000124700)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/node.go:434 +0x95c
github.com/lni/dragonboat.(*execEngine).saveSnapshot(0xc00026c460, 0x11, 0xc000208f00)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/execengine.go:241 +0x206
github.com/lni/dragonboat.(*execEngine).snapshotWorkerMain(0xc00026c460, 0x12)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/execengine.go:216 +0x4af
github.com/lni/dragonboat.newExecEngine.func3()
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/execengine.go:140 +0x33
github.com/lni/dragonboat/internal/utils/syncutil.(*Stopper).runWorker.func1(0xc0000b1e40, 0xc0000ba4d0, 0x0, 0x0, 0xc00024a500)
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/internal/utils/syncutil/stopper.go:91 +0x5d
created by github.com/lni/dragonboat/internal/utils/syncutil.(*Stopper).runWorker
	/home/boy/go/pkg/mod/github.com/lni/dragonboat@v0.0.0-20190314023311-56c27c5c18e2/internal/utils/syncutil/stopper.go:80 +0x98

```

I got panic when save sanpshot. using version v2.1.3.
I'm using multiplile goroutine to wirte
```
sess := n.nh.GetNoOPSession(clusterId)
v, err = n.nh.SyncPropose(cctx, sess, b)
```

**Comment by lni** [comment]
@gensmusic it seems to me that the total number of written bytes value returned by your SaveSnapshot method is incorrect. Please make sure you return the actual number of bytes written to the provided io.Writer

**Comment by gensmusic** [comment]
my bad. Thanks @lni .
