### ISSUE TITLE
potential memory leaks when using leveldb

### ISSUE THREAD

**Issue by JasonYuchen** [lni/dragonboat#56]
after passing all tests in dragonboat-cppwrapper-tests:
```
==1027==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 29568 byte(s) in 528 object(s) allocated from:
    #0 0x7f14dcc34458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x7f14dc38cba1 in leveldb_filterpolicy_create_bloom /home/jccai/go/src/github.com/lni/dragonboat/internal/logdb/levigo/deps_leveldb_db_c.cc:523

Indirect leak of 12672 byte(s) in 528 object(s) allocated from:
    #0 0x7f14dcc34458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
    #1 0x7f14dc3bd41c in leveldb::NewBloomFilterPolicy(int) /home/jccai/go/src/github.com/lni/dragonboat/internal/logdb/levigo/deps_leveldb_util_bloom.cc:92
```

**Comment by lni** [comment]
Thanks for reporting the issue, it has been fixed in master.
